### ISSUE TITLE
`this._tail` is only assigned and not being used?

### ISSUE THREAD

**Issue by apiep** [sindresorhus/yocto-queue#1]
Hi, while reading the source code `index.js` I notice that `this._tail` is not being used except only an assignment, is it intended or am I missing something?

**Comment by Richienb** [comment]
In JavaScript, when assigning a variable with an object you are simply keeping it as a reference. This means that when that specific value changes somewhere, every other reference changes as well - since they are all the same value.

`this._head` is an instance of `Node` which keeps track of its current value and nests another instance of `Node` that keeps the value that comes after it. When a value is provided to `enqueue`, the code needs to iterate through `this._head`, going deeper and deeper to find the last value. However, iterating through every single item is slow.

`yocto-queue` solves this problem by saving a reference to the last value as `this._tail` so that it can reference it to add a new value.

**Comment by sindresorhus** [comment]
Would maybe be useful to add a code comment in the file itself about this if anyone wanna do a PR.

**Comment by apiep** [comment]
Ah I see, what I missunderstood was on the performance part, and when the first item get `enqueue`ed the item got assigned to both `_head` and `_tail`.

Thanks for the explaination :)
